package com.example.stream.streamof;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Predicate;

import com.example.stream.streamtomap.Car;
// import com.google.common.base.Predicate;

public class streamConsumerSorted {

  public static void main(String[] args) {
    List<Car> list = new ArrayList<>();

    list.add(new Car(1, "Kia", "Sportage"));
    list.add(new Car(2, "Acura", "RDX"));
    list.add(new Car(3, "Volvo", "S60"));
    list.add(new Car(4, "Volkswagen", "Type 2"));
    list.add(new Car(5, "Audi", "Q5"));
    list.add(new Car(6, "Toyota", "Matrix"));
    list.add(new Car(7, "Mitsubishi", "Lancer"));
    list.add(new Car(8, "GMC", "Yukon XL 2500"));
    list.add(new Car(9, "Mitsubishi", "RVR"));
    list.add(new Car(10, "Toyota", "Venza"));
    list.add(new Car(11, "Ford", "Taurus"));
    list.add(new Car(12, "GMC", "Sierra"));
    list.add(new Car(13, "Mercedes-Benz", "C-Class"));
    list.add(new Car(14, "BMW", "Z4"));
    list.add(new Car(15, "Cadillac", "CTS"));
    list.add(new Car(16, "Volkswagen", "Cabriolet"));
    list.add(new Car(17, "Jeep", "Grand Cherokee"));
    list.add(new Car(18, "Infiniti", "Q"));
    list.add(new Car(19, "Pontiac", "Grand Am"));
    list.add(new Car(20, "Buick", "Coachbuilder"));
    list.add(new Car(21, "Cadillac", "Eldorado"));
    list.add(new Car(22, "Ford", "Thunderbird"));
    list.add(new Car(23, "BMW", "Z3"));
    list.add(new Car(24, "BMW", "M3"));
    list.add(new Car(25, "Pontiac", "Grand Prix"));
    list.add(new Car(26, "Lamborghini", "MurciÃ©lago"));
    list.add(new Car(27, "Honda", "Accord"));
    list.add(new Car(28, "Ferrari", "612 Scaglietti"));
    list.add(new Car(29, "Mercury", "Montego"));
    list.add(new Car(30, "Ford", "E250"));
    list.add(new Car(31, "Honda", "Pilot"));
    list.add(new Car(32, "Chevrolet", "S10"));
    list.add(new Car(33, "Ford", "Aerostar"));
    list.add(new Car(34, "GMC", "Canyon"));
    list.add(new Car(35, "Chevrolet", "Malibu"));
    list.add(new Car(36, "GMC", "Yukon XL 1500"));
    list.add(new Car(37, "Ford", "Mustang"));
    list.add(new Car(38, "Cadillac", "Seville"));
    list.add(new Car(39, "Ford", "Ranger"));
    list.add(new Car(40, "Buick", "Park Avenue"));
    list.add(new Car(41, "Toyota", "Sienna"));
    list.add(new Car(42, "Toyota", "4Runner"));
    list.add(new Car(43, "Mazda", "Mazda3"));
    list.add(new Car(44, "Mazda", "Miata MX-5"));
    list.add(new Car(45, "Chevrolet", "1500"));
    list.add(new Car(46, "Audi", "A8"));
    list.add(new Car(47, "Dodge", "Ram Van B250"));
    list.add(new Car(48, "Mazda", "B-Series Plus"));
    list.add(new Car(49, "Kia", "Sedona"));
    list.add(new Car(50, "Hyundai", "Tiburon"));
    list.add(new Car(51, "Geo", "Metro"));
    list.add(new Car(52, "Lincoln", "Town Car"));
    list.add(new Car(53, "Volkswagen", "Passat"));
    list.add(new Car(54, "Mercedes-Benz", "C-Class"));
    list.add(new Car(55, "Ford", "Mustang"));
    list.add(new Car(56, "Jaguar", "X-Type"));
    list.add(new Car(57, "Pontiac", "Grand Am"));
    list.add(new Car(58, "GMC", "Envoy XL"));
    list.add(new Car(59, "Buick", "LeSabre"));
    list.add(new Car(60, "Infiniti", "FX"));
    list.add(new Car(61, "Toyota", "Tercel"));
    list.add(new Car(62, "Honda", "del Sol"));
    list.add(new Car(63, "Maybach", "62"));
    list.add(new Car(64, "Dodge", "Avenger"));
    list.add(new Car(65, "BMW", "X5"));
    list.add(new Car(66, "Chevrolet", "Sportvan G30"));
    list.add(new Car(67, "Pontiac", "Solstice"));
    list.add(new Car(68, "GMC", "Savana"));
    list.add(new Car(69, "Lincoln", "Mark VIII"));
    list.add(new Car(70, "Ford", "F150"));
    list.add(new Car(71, "Saturn", "S-Series"));
    list.add(new Car(72, "Ford", "GT500"));
    list.add(new Car(73, "Lexus", "ES"));
    list.add(new Car(74, "Mitsubishi", "Montero Sport"));
    list.add(new Car(75, "Isuzu", "VehiCROSS"));
    list.add(new Car(76, "Buick", "Rainier"));
    list.add(new Car(77, "Ford", "F150"));
    list.add(new Car(78, "Toyota", "Tundra"));
    list.add(new Car(79, "Chevrolet", "Lumina"));
    list.add(new Car(80, "Nissan", "Cube"));
    list.add(new Car(81, "Mitsubishi", "Raider"));
    list.add(new Car(82, "Mercedes-Benz", "GL-Class"));
    list.add(new Car(83, "Nissan", "Pathfinder"));
    list.add(new Car(84, "Mitsubishi", "Mirage"));
    list.add(new Car(85, "Suzuki", "Grand Vitara"));
    list.add(new Car(86, "Nissan", "Sentra"));
    list.add(new Car(87, "Ford", "Focus"));
    list.add(new Car(88, "Saturn", "Outlook"));
    list.add(new Car(89, "Mercedes-Benz", "GL-Class"));
    list.add(new Car(90, "Volkswagen", "Passat"));
    list.add(new Car(91, "Saab", "43711"));
    list.add(new Car(92, "Pontiac", "Sunfire"));
    list.add(new Car(93, "Mercedes-Benz", "SL-Class"));
    list.add(new Car(94, "Buick", "Park Avenue"));
    list.add(new Car(95, "Mitsubishi", "Eclipse"));
    list.add(new Car(96, "Chevrolet", "3500"));
    list.add(new Car(97, "Volkswagen", "Golf"));
    list.add(new Car(98, "Nissan", "JUKE"));
    list.add(new Car(99, "Subaru", "Tribeca"));
    list.add(new Car(100, "Chevrolet", "Cavalier"));
    list.add(new Car(101, "Chevrolet", "Tahoe"));
    list.add(new Car(102, "Nissan", "Sentra"));
    list.add(new Car(103, "Honda", "Prelude"));
    list.add(new Car(104, "Buick", "LaCrosse"));
    list.add(new Car(105, "Mercedes-Benz", "M-Class"));
    list.add(new Car(106, "Dodge", "Ram 3500"));
    list.add(new Car(107, "Honda", "Passport"));
    list.add(new Car(108, "Porsche", "911"));
    list.add(new Car(109, "Ford", "Festiva"));
    list.add(new Car(110, "Saab", "900"));
    list.add(new Car(111, "Cadillac", "DeVille"));
    list.add(new Car(112, "Pontiac", "6000"));
    list.add(new Car(113, "Chevrolet", "Camaro"));
    list.add(new Car(114, "Mazda", "B-Series Plus"));
    list.add(new Car(115, "Eagle", "Vision"));
    list.add(new Car(116, "Volkswagen", "GTI"));
    list.add(new Car(117, "Toyota", "Tacoma Xtra"));
    list.add(new Car(118, "Subaru", "Impreza"));
    list.add(new Car(119, "Oldsmobile", "Achieva"));
    list.add(new Car(120, "Lincoln", "Continental"));
    list.add(new Car(121, "Acura", "RL"));
    list.add(new Car(122, "Lincoln", "Town Car"));
    list.add(new Car(123, "Acura", "ZDX"));
    list.add(new Car(124, "Mercedes-Benz", "CLS-Class"));
    list.add(new Car(125, "Daewoo", "Nubira"));
    list.add(new Car(126, "Oldsmobile", "98"));
    list.add(new Car(127, "Suzuki", "Grand Vitara"));
    list.add(new Car(128, "Oldsmobile", "Alero"));
    list.add(new Car(129, "Audi", "A3"));
    list.add(new Car(130, "Saturn", "Aura"));
    list.add(new Car(131, "Ford", "F150"));
    list.add(new Car(132, "Toyota", "Echo"));
    list.add(new Car(133, "Mercury", "Milan"));
    list.add(new Car(134, "Maserati", "430"));
    list.add(new Car(135, "Chevrolet", "SSR"));
    list.add(new Car(136, "Mercedes-Benz", "S-Class"));
    list.add(new Car(137, "Chevrolet", "3500"));
    list.add(new Car(138, "Ferrari", "458 Italia"));
    list.add(new Car(139, "Buick", "Regal"));
    list.add(new Car(140, "Dodge", "Ram 2500 Club"));
    list.add(new Car(141, "Mazda", "Millenia"));
    list.add(new Car(142, "Lexus", "IS"));
    list.add(new Car(143, "BMW", "Z4"));
    list.add(new Car(144, "Hyundai", "Elantra"));
    list.add(new Car(145, "Lexus", "LS"));
    list.add(new Car(146, "Nissan", "Armada"));
    list.add(new Car(147, "Chevrolet", "Malibu"));
    list.add(new Car(148, "Dodge", "Dakota Club"));
    list.add(new Car(149, "Chevrolet", "Suburban 2500"));
    list.add(new Car(150, "Chrysler", "Pacifica"));
    list.add(new Car(151, "Mazda", "929"));
    list.add(new Car(152, "Cadillac", "SRX"));
    list.add(new Car(153, "Nissan", "Cube"));
    list.add(new Car(154, "Plymouth", "Neon"));
    list.add(new Car(155, "Toyota", "Supra"));
    list.add(new Car(156, "Mitsubishi", "Montero Sport"));
    list.add(new Car(157, "Mazda", "B-Series Plus"));
    list.add(new Car(158, "Subaru", "XT"));
    list.add(new Car(159, "Honda", "Accord"));
    list.add(new Car(160, "Toyota", "Tacoma Xtra"));
    list.add(new Car(161, "Volvo", "S80"));
    list.add(new Car(162, "Bentley", "Arnage"));
    list.add(new Car(163, "Saturn", "S-Series"));
    list.add(new Car(164, "Infiniti", "G35"));
    list.add(new Car(165, "Toyota", "Tundra"));
    list.add(new Car(166, "Mercedes-Benz", "SLR McLaren"));
    list.add(new Car(167, "Acura", "CL"));
    list.add(new Car(168, "Mitsubishi", "Chariot"));
    list.add(new Car(169, "Lincoln", "Navigator"));
    list.add(new Car(170, "BMW", "M3"));
    list.add(new Car(171, "Kia", "Sephia"));
    list.add(new Car(172, "Dodge", "Grand Caravan"));
    list.add(new Car(173, "Cadillac", "DeVille"));
    list.add(new Car(174, "Nissan", "Altima"));
    list.add(new Car(175, "Mitsubishi", "Eclipse"));
    list.add(new Car(176, "Cadillac", "XLR"));
    list.add(new Car(177, "Ford", "Aerostar"));
    list.add(new Car(178, "Ford", "Mustang"));
    list.add(new Car(179, "Aston Martin", "Vanquish S"));
    list.add(new Car(180, "Dodge", "Intrepid"));
    list.add(new Car(181, "Volvo", "C70"));
    list.add(new Car(182, "Acura", "Legend"));
    list.add(new Car(183, "Hyundai", "HED-5"));
    list.add(new Car(184, "Spyker", "C8 Spyder"));
    list.add(new Car(185, "Nissan", "300ZX"));
    list.add(new Car(186, "Nissan", "Rogue"));
    list.add(new Car(187, "Mazda", "Miata MX-5"));
    list.add(new Car(188, "Infiniti", "QX"));
    list.add(new Car(189, "Mitsubishi", "Pajero"));
    list.add(new Car(190, "Jeep", "Wrangler"));
    list.add(new Car(191, "Geo", "Metro"));
    list.add(new Car(192, "Lexus", "IS"));
    list.add(new Car(193, "Dodge", "Ram Van 1500"));
    list.add(new Car(194, "Pontiac", "Grand Prix"));
    list.add(new Car(195, "Scion", "xB"));
    list.add(new Car(196, "Volkswagen", "Golf"));
    list.add(new Car(197, "GMC", "Savana"));
    list.add(new Car(198, "GMC", "Yukon XL 2500"));
    list.add(new Car(199, "Mercedes-Benz", "G-Class"));
    list.add(new Car(200, "Aston Martin", "V8 Vantage"));
    list.add(new Car(201, "Hyundai", "Sonata"));
    list.add(new Car(202, "Mitsubishi", "Pajero"));
    list.add(new Car(203, "Honda", "Element"));
    list.add(new Car(204, "Isuzu", "Space"));
    list.add(new Car(205, "Pontiac", "Tempest"));
    list.add(new Car(206, "Volkswagen", "Jetta"));
    list.add(new Car(207, "Volkswagen", "Jetta"));
    list.add(new Car(208, "Oldsmobile", "Silhouette"));
    list.add(new Car(209, "Lexus", "LX"));
    list.add(new Car(210, "Suzuki", "SX4"));
    list.add(new Car(211, "Ford", "Thunderbird"));
    list.add(new Car(212, "Suzuki", "Grand Vitara"));
    list.add(new Car(213, "Saab", "900"));
    list.add(new Car(214, "Ford", "Econoline E250"));
    list.add(new Car(215, "Chevrolet", "2500"));
    list.add(new Car(216, "GMC", "Rally Wagon G3500"));
    list.add(new Car(217, "Toyota", "Camry"));
    list.add(new Car(218, "Nissan", "Pathfinder"));
    list.add(new Car(219, "Toyota", "4Runner"));
    list.add(new Car(220, "Ford", "Explorer Sport Trac"));
    list.add(new Car(221, "Pontiac", "GTO"));
    list.add(new Car(222, "Mercedes-Benz", "G-Class"));
    list.add(new Car(223, "Chevrolet", "Tahoe"));
    list.add(new Car(224, "Lamborghini", "Gallardo"));
    list.add(new Car(225, "Mitsubishi", "Galant"));
    list.add(new Car(226, "Mitsubishi", "Starion"));
    list.add(new Car(227, "Chevrolet", "Corvette"));
    list.add(new Car(228, "Pontiac", "Vibe"));
    list.add(new Car(229, "Plymouth", "Laser"));
    list.add(new Car(230, "Toyota", "Matrix"));
    list.add(new Car(231, "Chevrolet", "Camaro"));
    list.add(new Car(232, "Ford", "F-Series"));
    list.add(new Car(233, "Oldsmobile", "Cutlass"));
    list.add(new Car(234, "GMC", "Yukon XL 1500"));
    list.add(new Car(235, "Eagle", "Vision"));
    list.add(new Car(236, "Volvo", "V50"));
    list.add(new Car(237, "Ford", "F250"));
    list.add(new Car(238, "Ford", "Explorer"));
    list.add(new Car(239, "Suzuki", "Swift"));
    list.add(new Car(240, "BMW", "M5"));
    list.add(new Car(241, "Mitsubishi", "GTO"));
    list.add(new Car(242, "Lexus", "GS"));
    list.add(new Car(243, "Mitsubishi", "Mirage"));
    list.add(new Car(244, "Honda", "Civic"));
    list.add(new Car(245, "Mercury", "Mountaineer"));
    list.add(new Car(246, "Chevrolet", "APV"));
    list.add(new Car(247, "Dodge", "Grand Caravan"));
    list.add(new Car(248, "Volvo", "V50"));
    list.add(new Car(249, "Buick", "Rendezvous"));
    list.add(new Car(250, "Chevrolet", "Cruze"));
    list.add(new Car(251, "Chrysler", "300M"));
    list.add(new Car(252, "Nissan", "Armada"));
    list.add(new Car(253, "Ford", "Escape"));
    list.add(new Car(254, "Mercury", "Cougar"));
    list.add(new Car(255, "Lamborghini", "Gallardo"));
    list.add(new Car(256, "Pontiac", "Sunbird"));
    list.add(new Car(257, "GMC", "Sierra 3500"));
    list.add(new Car(258, "Mercedes-Benz", "E-Class"));
    list.add(new Car(259, "Ford", "Escape"));
    list.add(new Car(260, "Oldsmobile", "Ciera"));
    list.add(new Car(261, "Ford", "Expedition"));
    list.add(new Car(262, "Lexus", "LS"));
    list.add(new Car(263, "Mitsubishi", "Pajero"));
    list.add(new Car(264, "Ford", "Mustang"));
    list.add(new Car(265, "GMC", "3500 Club Coupe"));
    list.add(new Car(266, "Cadillac", "CTS"));
    list.add(new Car(267, "Mercury", "Mountaineer"));
    list.add(new Car(268, "Smart", "Fortwo"));
    list.add(new Car(269, "Chrysler", "Town & Country"));
    list.add(new Car(270, "Nissan", "300ZX"));
    list.add(new Car(271, "Saab", "43711"));
    list.add(new Car(272, "Land Rover", "Range Rover Sport"));
    list.add(new Car(273, "Audi", "90"));
    list.add(new Car(274, "BMW", "7 Series"));
    list.add(new Car(275, "Ford", "LTD"));
    list.add(new Car(276, "GMC", "Savana 1500"));
    list.add(new Car(277, "Porsche", "928"));
    list.add(new Car(278, "Ford", "Taurus"));
    list.add(new Car(279, "Ferrari", "458 Italia"));
    list.add(new Car(280, "Mitsubishi", "GTO"));
    list.add(new Car(281, "Volvo", "V70"));
    list.add(new Car(282, "Infiniti", "QX"));
    list.add(new Car(283, "Toyota", "Solara"));
    list.add(new Car(284, "Honda", "del Sol"));
    list.add(new Car(285, "Lincoln", "Continental"));
    list.add(new Car(286, "Lincoln", "Navigator"));
    list.add(new Car(287, "Dodge", "Ram Wagon B150"));
    list.add(new Car(288, "Volvo", "S90"));
    list.add(new Car(289, "Ford", "Lightning"));
    list.add(new Car(290, "Hyundai", "Tiburon"));
    list.add(new Car(291, "GMC", "Sonoma Club Coupe"));
    list.add(new Car(292, "Saturn", "Sky"));
    list.add(new Car(293, "Infiniti", "I"));
    list.add(new Car(294, "Land Rover", "Discovery"));
    list.add(new Car(295, "Dodge", "Grand Caravan"));
    list.add(new Car(296, "Mitsubishi", "Lancer"));
    list.add(new Car(297, "Mercedes-Benz", "CLS-Class"));
    list.add(new Car(298, "Mercedes-Benz", "CL-Class"));
    list.add(new Car(299, "Toyota", "Tacoma Xtra"));
    list.add(new Car(300, "Ford", "Crown Victoria"));
    list.add(new Car(301, "BMW", "M3"));
    list.add(new Car(302, "Ford", "F-Series"));
    list.add(new Car(303, "Dodge", "Caravan"));
    list.add(new Car(304, "Jaguar", "XJ Series"));
    list.add(new Car(305, "Subaru", "Tribeca"));
    list.add(new Car(306, "BMW", "X3"));
    list.add(new Car(307, "Ford", "Tempo"));
    list.add(new Car(308, "Mazda", "B-Series"));
    list.add(new Car(309, "Volvo", "S40"));
    list.add(new Car(310, "Toyota", "Avalon"));
    list.add(new Car(311, "Chevrolet", "Suburban 1500"));
    list.add(new Car(312, "Mitsubishi", "Pajero"));
    list.add(new Car(313, "Audi", "R8"));
    list.add(new Car(314, "BMW", "Z3"));
    list.add(new Car(315, "Nissan", "Altima"));
    list.add(new Car(316, "Dodge", "Ram 1500"));
    list.add(new Car(317, "Kia", "Sportage"));
    list.add(new Car(318, "Scion", "xB"));
    list.add(new Car(319, "Saturn", "Relay"));
    list.add(new Car(320, "Chevrolet", "Monte Carlo"));
    list.add(new Car(321, "BMW", "M3"));
    list.add(new Car(322, "Bentley", "Continental"));
    list.add(new Car(323, "Land Rover", "Defender"));
    list.add(new Car(324, "Mercedes-Benz", "GLK-Class"));
    list.add(new Car(325, "Chevrolet", "Camaro"));
    list.add(new Car(326, "Isuzu", "Ascender"));
    list.add(new Car(327, "Mitsubishi", "RVR"));
    list.add(new Car(328, "Volvo", "C70"));
    list.add(new Car(329, "Lexus", "ES"));
    list.add(new Car(330, "Saab", "900"));
    list.add(new Car(331, "Chevrolet", "Tahoe"));
    list.add(new Car(332, "BMW", "5 Series"));
    list.add(new Car(333, "Saturn", "VUE"));
    list.add(new Car(334, "Infiniti", "G37"));
    list.add(new Car(335, "GMC", "Sierra 2500"));
    list.add(new Car(336, "Kia", "Sedona"));
    list.add(new Car(337, "GMC", "Envoy"));
    list.add(new Car(338, "Hyundai", "Veracruz"));
    list.add(new Car(339, "Volkswagen", "Passat"));
    list.add(new Car(340, "Ford", "GT500"));
    list.add(new Car(341, "Audi", "Cabriolet"));
    list.add(new Car(342, "Dodge", "Grand Caravan"));
    list.add(new Car(343, "Chevrolet", "S10 Blazer"));
    list.add(new Car(344, "Oldsmobile", "Bravada"));
    list.add(new Car(345, "Nissan", "Frontier"));
    list.add(new Car(346, "Ford", "Taurus"));
    list.add(new Car(347, "Chrysler", "PT Cruiser"));
    list.add(new Car(348, "Land Rover", "Discovery"));
    list.add(new Car(349, "Ford", "Flex"));
    list.add(new Car(350, "Lexus", "GS"));
    list.add(new Car(351, "Audi", "A5"));
    list.add(new Car(352, "Subaru", "Tribeca"));
    list.add(new Car(353, "Pontiac", "6000"));
    list.add(new Car(354, "Isuzu", "Amigo"));
    list.add(new Car(355, "Nissan", "Xterra"));
    list.add(new Car(356, "Jeep", "Commander"));
    list.add(new Car(357, "GMC", "Sierra 1500"));
    list.add(new Car(358, "Oldsmobile", "Cutlass"));
    list.add(new Car(359, "Ford", "F350"));
    list.add(new Car(360, "Mazda", "626"));
    list.add(new Car(361, "Porsche", "Boxster"));
    list.add(new Car(362, "Hyundai", "Sonata"));
    list.add(new Car(363, "Lincoln", "Aviator"));
    list.add(new Car(364, "Jeep", "Grand Cherokee"));
    list.add(new Car(365, "Audi", "Quattro"));
    list.add(new Car(366, "Subaru", "Legacy"));
    list.add(new Car(367, "Suzuki", "XL-7"));
    list.add(new Car(368, "Ford", "Mustang"));
    list.add(new Car(369, "Audi", "A6"));
    list.add(new Car(370, "Audi", "Q5"));
    list.add(new Car(371, "Ford", "Aerostar"));
    list.add(new Car(372, "GMC", "Savana 2500"));
    list.add(new Car(373, "Suzuki", "Daewoo Lacetti"));
    list.add(new Car(374, "Cadillac", "CTS"));
    list.add(new Car(375, "Audi", "S4"));
    list.add(new Car(376, "Suzuki", "Aerio"));
    list.add(new Car(377, "Lincoln", "Navigator"));
    list.add(new Car(378, "Cadillac", "Fleetwood"));
    list.add(new Car(379, "Jaguar", "XK Series"));
    list.add(new Car(380, "Chevrolet", "Suburban 1500"));
    list.add(new Car(381, "Pontiac", "Bonneville"));
    list.add(new Car(382, "Saab", "9000"));
    list.add(new Car(383, "Mitsubishi", "Outlander"));
    list.add(new Car(384, "Audi", "S4"));
    list.add(new Car(385, "Mitsubishi", "Galant"));
    list.add(new Car(386, "Mitsubishi", "Montero"));
    list.add(new Car(387, "Saab", "9000"));
    list.add(new Car(388, "GMC", "3500 Club Coupe"));
    list.add(new Car(389, "GMC", "Savana 1500"));
    list.add(new Car(390, "Nissan", "Pathfinder"));
    list.add(new Car(391, "Mercury", "Sable"));
    list.add(new Car(392, "Ford", "Explorer"));
    list.add(new Car(393, "Mercedes-Benz", "SL-Class"));
    list.add(new Car(394, "Lexus", "SC"));
    list.add(new Car(395, "Lincoln", "Continental"));
    list.add(new Car(396, "Honda", "Odyssey"));
    list.add(new Car(397, "Dodge", "Caliber"));
    list.add(new Car(398, "Pontiac", "Trans Sport"));
    list.add(new Car(399, "BMW", "5 Series"));
    list.add(new Car(400, "Hyundai", "Tiburon"));
    list.add(new Car(401, "Ford", "Escape"));
    list.add(new Car(402, "Chrysler", "300"));
    list.add(new Car(403, "Hyundai", "Accent"));
    list.add(new Car(404, "Ford", "Crown Victoria"));
    list.add(new Car(405, "Chrysler", "Pacifica"));
    list.add(new Car(406, "GMC", "Envoy"));
    list.add(new Car(407, "Mitsubishi", "Montero"));
    list.add(new Car(408, "Honda", "Accord"));
    list.add(new Car(409, "Ford", "Econoline E150"));
    list.add(new Car(410, "Ford", "Club Wagon"));
    list.add(new Car(411, "Dodge", "Colt"));
    list.add(new Car(412, "Lexus", "RX"));
    list.add(new Car(413, "Mercedes-Benz", "CL65 AMG"));
    list.add(new Car(414, "Isuzu", "Rodeo Sport"));
    list.add(new Car(415, "Isuzu", "Trooper"));
    list.add(new Car(416, "Mercury", "Cougar"));
    list.add(new Car(417, "GMC", "3500"));
    list.add(new Car(418, "Pontiac", "Grand Am"));
    list.add(new Car(419, "Audi", "Q7"));
    list.add(new Car(420, "Jaguar", "XK Series"));
    list.add(new Car(421, "Mercury", "Sable"));
    list.add(new Car(422, "Chevrolet", "Silverado 2500"));
    list.add(new Car(423, "Volkswagen", "Fox"));
    list.add(new Car(424, "Audi", "200"));
    list.add(new Car(425, "MINI", "Cooper Clubman"));
    list.add(new Car(426, "Mazda", "RX-7"));
    list.add(new Car(427, "Hyundai", "Accent"));
    list.add(new Car(428, "Mercedes-Benz", "M-Class"));
    list.add(new Car(429, "Aston Martin", "V8 Vantage"));
    list.add(new Car(430, "Chevrolet", "Corsica"));
    list.add(new Car(431, "Ford", "Windstar"));
    list.add(new Car(432, "Mercury", "Capri"));
    list.add(new Car(433, "Suzuki", "XL7"));
    list.add(new Car(434, "BMW", "X5 M"));
    list.add(new Car(435, "Chevrolet", "Blazer"));
    list.add(new Car(436, "Dodge", "Colt"));
    list.add(new Car(437, "Mercedes-Benz", "C-Class"));
    list.add(new Car(438, "Volkswagen", "New Beetle"));
    list.add(new Car(439, "Porsche", "911"));
    list.add(new Car(440, "Mercedes-Benz", "CLK-Class"));
    list.add(new Car(441, "Mazda", "626"));
    list.add(new Car(442, "Buick", "Regal"));
    list.add(new Car(443, "Subaru", "Outback"));
    list.add(new Car(444, "Ford", "Falcon"));
    list.add(new Car(445, "Toyota", "Corolla"));
    list.add(new Car(446, "Pontiac", "G8"));
    list.add(new Car(447, "Buick", "Skylark"));
    list.add(new Car(448, "GMC", "Jimmy"));
    list.add(new Car(449, "Acura", "TL"));
    list.add(new Car(450, "Kia", "Rio"));
    list.add(new Car(451, "Oldsmobile", "Cutlass"));
    list.add(new Car(452, "Ford", "Mustang"));
    list.add(new Car(453, "Oldsmobile", "Achieva"));
    list.add(new Car(454, "Toyota", "Xtra"));
    list.add(new Car(455, "Chevrolet", "Corvette"));
    list.add(new Car(456, "Cadillac", "DeVille"));
    list.add(new Car(457, "GMC", "Vandura G3500"));
    list.add(new Car(458, "Volkswagen", "Corrado"));
    list.add(new Car(459, "Pontiac", "GTO"));
    list.add(new Car(460, "GMC", "Sierra 3500"));
    list.add(new Car(461, "Ford", "Escape"));
    list.add(new Car(462, "Lexus", "GS"));
    list.add(new Car(463, "Mitsubishi", "Montero"));
    list.add(new Car(464, "Land Rover", "Range Rover"));
    list.add(new Car(465, "Plymouth", "Grand Voyager"));
    list.add(new Car(466, "Bentley", "Azure"));
    list.add(new Car(467, "Porsche", "Cayenne"));
    list.add(new Car(468, "Audi", "riolet"));
    list.add(new Car(469, "GMC", "Sierra Hybrid"));
    list.add(new Car(470, "Dodge", "Daytona"));
    list.add(new Car(471, "Mercury", "Grand Marquis"));
    list.add(new Car(472, "Dodge", "Durango"));
    list.add(new Car(473, "Chrysler", "Concorde"));
    list.add(new Car(474, "GMC", "Suburban 2500"));
    list.add(new Car(475, "Land Rover", "Range Rover"));
    list.add(new Car(476, "Jaguar", "XK"));
    list.add(new Car(477, "Toyota", "4Runner"));
    list.add(new Car(478, "BMW", "X5"));
    list.add(new Car(479, "Suzuki", "Forenza"));
    list.add(new Car(480, "Mercedes-Benz", "S-Class"));
    list.add(new Car(481, "Chevrolet", "Express 1500"));
    list.add(new Car(482, "Nissan", "Pathfinder"));
    list.add(new Car(483, "Dodge", "Durango"));
    list.add(new Car(484, "Toyota", "Matrix"));
    list.add(new Car(485, "Mercedes-Benz", "300CE"));
    list.add(new Car(486, "Pontiac", "Firebird"));
    list.add(new Car(487, "Scion", "tC"));
    list.add(new Car(488, "GMC", "Sonoma"));
    list.add(new Car(489, "Ford", "Festiva"));
    list.add(new Car(490, "Chevrolet", "Avalanche 1500"));
    list.add(new Car(491, "Suzuki", "Grand Vitara"));
    list.add(new Car(492, "Pontiac", "Grand Prix"));
    list.add(new Car(493, "Volkswagen", "GTI"));
    list.add(new Car(494, "Chevrolet", "Silverado 1500"));
    list.add(new Car(495, "Maybach", "62"));
    list.add(new Car(496, "Pontiac", "Bonneville"));
    list.add(new Car(497, "Nissan", "Cube"));
    list.add(new Car(498, "BMW", "3 Series"));
    list.add(new Car(499, "Acura", "RL"));
    list.add(new Car(500, "Porsche", "944"));
    list.add(new Car(501, "Pontiac", "Bonneville"));
    list.add(new Car(502, "Ford", "E-Series"));
    list.add(new Car(503, "Suzuki", "Esteem"));
    list.add(new Car(504, "Mercury", "Topaz"));
    list.add(new Car(505, "Chevrolet", "Cobalt SS"));
    list.add(new Car(506, "Ford", "E-Series"));
    list.add(new Car(507, "Bentley", "Continental"));
    list.add(new Car(508, "Jeep", "Compass"));
    list.add(new Car(509, "Ford", "Crown Victoria"));
    list.add(new Car(510, "Mercury", "Mariner"));
    list.add(new Car(511, "Honda", "Insight"));
    list.add(new Car(512, "Dodge", "Dakota Club"));
    list.add(new Car(513, "Mitsubishi", "Challenger"));
    list.add(new Car(514, "Chevrolet", "2500"));
    list.add(new Car(515, "Saturn", "S-Series"));
    list.add(new Car(516, "Infiniti", "QX"));
    list.add(new Car(517, "Pontiac", "Torrent"));
    list.add(new Car(518, "Dodge", "Ram 1500"));
    list.add(new Car(519, "Buick", "Coachbuilder"));
    list.add(new Car(520, "Pontiac", "Vibe"));
    list.add(new Car(521, "Dodge", "Ram 2500"));
    list.add(new Car(522, "Pontiac", "6000"));
    list.add(new Car(523, "Dodge", "Avenger"));
    list.add(new Car(524, "Audi", "A8"));
    list.add(new Car(525, "Chevrolet", "Uplander"));
    list.add(new Car(526, "GMC", "Jimmy"));
    list.add(new Car(527, "Maserati", "GranTurismo"));
    list.add(new Car(528, "Pontiac", "6000"));
    list.add(new Car(529, "Toyota", "Avalon"));
    list.add(new Car(530, "MINI", "Cooper"));
    list.add(new Car(531, "Ford", "Escort"));
    list.add(new Car(532, "Mazda", "B-Series"));
    list.add(new Car(533, "Lexus", "GS"));
    list.add(new Car(534, "Volkswagen", "Jetta"));
    list.add(new Car(535, "Ferrari", "430 Scuderia"));
    list.add(new Car(536, "MINI", "MINI"));
    list.add(new Car(537, "Dodge", "Avenger"));
    list.add(new Car(538, "Hyundai", "Sonata"));
    list.add(new Car(539, "Jaguar", "XJ Series"));
    list.add(new Car(540, "Ford", "F150"));
    list.add(new Car(541, "Audi", "S4"));
    list.add(new Car(542, "Dodge", "Stealth"));
    list.add(new Car(543, "Ford", "Fairlane"));
    list.add(new Car(544, "Hyundai", "Veracruz"));
    list.add(new Car(545, "Chrysler", "LeBaron"));
    list.add(new Car(546, "Volkswagen", "Passat"));
    list.add(new Car(547, "Jeep", "Cherokee"));
    list.add(new Car(548, "Honda", "Civic GX"));
    list.add(new Car(549, "Mazda", "CX-9"));
    list.add(new Car(550, "Cadillac", "STS"));
    list.add(new Car(551, "Mercury", "Marquis"));
    list.add(new Car(552, "Mitsubishi", "Mirage"));
    list.add(new Car(553, "Acura", "MDX"));
    list.add(new Car(554, "Plymouth", "Prowler"));
    list.add(new Car(555, "Mercedes-Benz", "SL-Class"));
    list.add(new Car(556, "Volkswagen", "Touareg"));
    list.add(new Car(557, "Lexus", "CT"));
    list.add(new Car(558, "Aston Martin", "DBS"));
    list.add(new Car(559, "Dodge", "D250 Club"));
    list.add(new Car(560, "Isuzu", "Impulse"));
    list.add(new Car(561, "Toyota", "4Runner"));
    list.add(new Car(562, "GMC", "Suburban 2500"));
    list.add(new Car(563, "Ford", "Tempo"));
    list.add(new Car(564, "Mazda", "MPV"));
    list.add(new Car(565, "Mitsubishi", "Starion"));
    list.add(new Car(566, "Chevrolet", "Camaro"));
    list.add(new Car(567, "Ford", "ZX2"));
    list.add(new Car(568, "Land Rover", "Range Rover Evoque"));
    list.add(new Car(569, "GMC", "Sonoma"));
    list.add(new Car(570, "Lexus", "RX"));
    list.add(new Car(571, "Honda", "Accord"));
    list.add(new Car(572, "BMW", "1 Series"));
    list.add(new Car(573, "Ford", "Transit Connect"));
    list.add(new Car(574, "Buick", "Century"));
    list.add(new Car(575, "Subaru", "Alcyone SVX"));
    list.add(new Car(576, "Land Rover", "Defender"));
    list.add(new Car(577, "Ford", "Escort"));
    list.add(new Car(578, "Dodge", "Sprinter"));
    list.add(new Car(579, "Mercury", "Cougar"));
    list.add(new Car(580, "Mazda", "626"));
    list.add(new Car(581, "Subaru", "Outback"));
    list.add(new Car(582, "Hyundai", "Santa Fe"));
    list.add(new Car(583, "Honda", "Civic"));
    list.add(new Car(584, "Isuzu", "Trooper"));
    list.add(new Car(585, "Pontiac", "Grand Prix"));
    list.add(new Car(586, "Volvo", "C30"));
    list.add(new Car(587, "Geo", "Tracker"));
    list.add(new Car(588, "Pontiac", "Solstice"));
    list.add(new Car(589, "Lexus", "IS"));
    list.add(new Car(590, "GMC", "1500 Club Coupe"));
    list.add(new Car(591, "BMW", "545"));
    list.add(new Car(592, "Subaru", "Legacy"));
    list.add(new Car(593, "Pontiac", "Vibe"));
    list.add(new Car(594, "Lincoln", "Continental Mark VII"));
    list.add(new Car(595, "Lotus", "Elise"));
    list.add(new Car(596, "Chevrolet", "Tahoe"));
    list.add(new Car(597, "Mazda", "Mazdaspeed 3"));
    list.add(new Car(598, "Isuzu", "Rodeo"));
    list.add(new Car(599, "Cadillac", "DTS"));
    list.add(new Car(600, "Volvo", "XC60"));
    list.add(new Car(601, "Honda", "Accord"));
    list.add(new Car(602, "Lincoln", "Navigator"));
    list.add(new Car(603, "Mitsubishi", "Mirage"));
    list.add(new Car(604, "Chevrolet", "Suburban 2500"));
    list.add(new Car(605, "Chevrolet", "S10"));
    list.add(new Car(606, "Toyota", "Solara"));
    list.add(new Car(607, "Lexus", "LS"));
    list.add(new Car(608, "Buick", "Skyhawk"));
    list.add(new Car(609, "Pontiac", "Montana"));
    list.add(new Car(610, "Mitsubishi", "Starion"));
    list.add(new Car(611, "Porsche", "Cayman"));
    list.add(new Car(612, "Isuzu", "Ascender"));
    list.add(new Car(613, "Saturn", "Aura"));
    list.add(new Car(614, "Chevrolet", "Caprice Classic"));
    list.add(new Car(615, "Pontiac", "GTO"));
    list.add(new Car(616, "Nissan", "Versa"));
    list.add(new Car(617, "Porsche", "911"));
    list.add(new Car(618, "GMC", "Savana 2500"));
    list.add(new Car(619, "Scion", "tC"));
    list.add(new Car(620, "Suzuki", "Swift"));
    list.add(new Car(621, "Toyota", "MR2"));
    list.add(new Car(622, "Volvo", "XC70"));
    list.add(new Car(623, "GMC", "Sonoma"));
    list.add(new Car(624, "Land Rover", "Freelander"));
    list.add(new Car(625, "Volvo", "V70"));
    list.add(new Car(626, "Saab", "900"));
    list.add(new Car(627, "Dodge", "Caliber"));
    list.add(new Car(628, "Isuzu", "Oasis"));
    list.add(new Car(629, "Jeep", "Wrangler"));
    list.add(new Car(630, "Chevrolet", "Camaro"));
    list.add(new Car(631, "Toyota", "MR2"));
    list.add(new Car(632, "Chrysler", "Crossfire Roadster"));
    list.add(new Car(633, "Jeep", "Wrangler"));
    list.add(new Car(634, "Dodge", "Ram"));
    list.add(new Car(635, "Ford", "Escape"));
    list.add(new Car(636, "Hyundai", "Sonata"));
    list.add(new Car(637, "Chrysler", "300"));
    list.add(new Car(638, "Ford", "E150"));
    list.add(new Car(639, "Kia", "Sportage"));
    list.add(new Car(640, "GMC", "Yukon"));
    list.add(new Car(641, "Lexus", "LX"));
    list.add(new Car(642, "Audi", "S6"));
    list.add(new Car(643, "Hyundai", "Genesis"));
    list.add(new Car(644, "Chevrolet", "Express 3500"));
    list.add(new Car(645, "Mercedes-Benz", "SL-Class"));
    list.add(new Car(646, "Pontiac", "Bonneville"));
    list.add(new Car(647, "Jaguar", "XJ Series"));
    list.add(new Car(648, "Dodge", "Intrepid"));
    list.add(new Car(649, "Mercedes-Benz", "S-Class"));
    list.add(new Car(650, "Honda", "Civic Si"));
    list.add(new Car(651, "BMW", "5 Series"));
    list.add(new Car(652, "Aston Martin", "V8 Vantage S"));
    list.add(new Car(653, "Toyota", "Supra"));
    list.add(new Car(654, "Ford", "Explorer"));
    list.add(new Car(655, "Toyota", "Previa"));
    list.add(new Car(656, "Toyota", "Camry"));
    list.add(new Car(657, "Audi", "riolet"));
    list.add(new Car(658, "Volvo", "S70"));
    list.add(new Car(659, "Mercedes-Benz", "C-Class"));
    list.add(new Car(660, "Toyota", "Matrix"));
    list.add(new Car(661, "Volvo", "850"));
    list.add(new Car(662, "Mercedes-Benz", "R-Class"));
    list.add(new Car(663, "Maserati", "Karif"));
    list.add(new Car(664, "Ford", "Focus"));
    list.add(new Car(665, "Mitsubishi", "Montero Sport"));
    list.add(new Car(666, "Alfa Romeo", "164"));
    list.add(new Car(667, "GMC", "Savana 3500"));
    list.add(new Car(668, "Chevrolet", "1500"));
    list.add(new Car(669, "Chevrolet", "Corvette"));
    list.add(new Car(670, "Ford", "Explorer Sport Trac"));
    list.add(new Car(671, "Maserati", "Spyder"));
    list.add(new Car(672, "Volvo", "S40"));
    list.add(new Car(673, "Lexus", "LS"));
    list.add(new Car(674, "Dodge", "Dakota Club"));
    list.add(new Car(675, "Isuzu", "Trooper"));
    list.add(new Car(676, "Buick", "Reatta"));
    list.add(new Car(677, "Jeep", "Liberty"));
    list.add(new Car(678, "Mazda", "MX-3"));
    list.add(new Car(679, "Mercedes-Benz", "300SE"));
    list.add(new Car(680, "Ford", "Bronco II"));
    list.add(new Car(681, "Lexus", "GX"));
    list.add(new Car(682, "Cadillac", "Escalade"));
    list.add(new Car(683, "Mazda", "Miata MX-5"));
    list.add(new Car(684, "Pontiac", "Trans Sport"));
    list.add(new Car(685, "Nissan", "Maxima"));
    list.add(new Car(686, "Mitsubishi", "Truck"));
    list.add(new Car(687, "Cadillac", "Allante"));
    list.add(new Car(688, "Ford", "Edge"));
    list.add(new Car(689, "Audi", "A3"));
    list.add(new Car(690, "Chevrolet", "Tahoe"));
    list.add(new Car(691, "Mercury", "Topaz"));
    list.add(new Car(692, "Chrysler", "Sebring"));
    list.add(new Car(693, "Chevrolet", "Corvette"));
    list.add(new Car(694, "Ford", "F450"));
    list.add(new Car(695, "Dodge", "Ram 1500 Club"));
    list.add(new Car(696, "Buick", "Rendezvous"));
    list.add(new Car(697, "Nissan", "Murano"));
    list.add(new Car(698, "Volvo", "S80"));
    list.add(new Car(699, "GMC", "Sierra 1500"));
    list.add(new Car(700, "Mercedes-Benz", "S-Class"));
    list.add(new Car(701, "GMC", "3500 Club Coupe"));
    list.add(new Car(702, "Mitsubishi", "Mirage"));
    list.add(new Car(703, "Lamborghini", "Gallardo"));
    list.add(new Car(704, "Subaru", "Legacy"));
    list.add(new Car(705, "Mercury", "Cougar"));
    list.add(new Car(706, "Porsche", "911"));
    list.add(new Car(707, "Toyota", "Solara"));
    list.add(new Car(708, "Chevrolet", "Express 1500"));
    list.add(new Car(709, "Mitsubishi", "Diamante"));
    list.add(new Car(710, "Ford", "E-Series"));
    list.add(new Car(711, "Honda", "Civic"));
    list.add(new Car(712, "Chevrolet", "Suburban 1500"));
    list.add(new Car(713, "Chrysler", "Fifth Ave"));
    list.add(new Car(714, "Isuzu", "Trooper"));
    list.add(new Car(715, "Porsche", "Boxster"));
    list.add(new Car(716, "Toyota", "Land Cruiser"));
    list.add(new Car(717, "Volkswagen", "Cabriolet"));
    list.add(new Car(718, "Chevrolet", "Suburban"));
    list.add(new Car(719, "Mercedes-Benz", "190E"));
    list.add(new Car(720, "Geo", "Metro"));
    list.add(new Car(721, "GMC", "3500 Club Coupe"));
    list.add(new Car(722, "GMC", "Sierra Hybrid"));
    list.add(new Car(723, "Bentley", "Continental GTC"));
    list.add(new Car(724, "Kia", "Soul"));
    list.add(new Car(725, "Ford", "Explorer"));
    list.add(new Car(726, "Mercedes-Benz", "S-Class"));
    list.add(new Car(727, "Lexus", "IS F"));
    list.add(new Car(728, "Kia", "Sorento"));
    list.add(new Car(729, "Toyota", "Prius Plug-in Hybrid"));
    list.add(new Car(730, "Pontiac", "Grand Prix"));
    list.add(new Car(731, "Dodge", "Caliber"));
    list.add(new Car(732, "Infiniti", "FX"));
    list.add(new Car(733, "GMC", "Yukon"));
    list.add(new Car(734, "BMW", "7 Series"));
    list.add(new Car(735, "Subaru", "Impreza"));
    list.add(new Car(736, "Mercury", "Grand Marquis"));
    list.add(new Car(737, "Nissan", "Xterra"));
    list.add(new Car(738, "Hummer", "H3"));
    list.add(new Car(739, "Honda", "Accord"));
    list.add(new Car(740, "Pontiac", "Fiero"));
    list.add(new Car(741, "Dodge", "Caravan"));
    list.add(new Car(742, "Mercury", "Tracer"));
    list.add(new Car(743, "Dodge", "Nitro"));
    list.add(new Car(744, "Saab", "9-4X"));
    list.add(new Car(745, "Land Rover", "Range Rover"));
    list.add(new Car(746, "Chevrolet", "Suburban 1500"));
    list.add(new Car(747, "Mercedes-Benz", "E-Class"));
    list.add(new Car(748, "Chevrolet", "Corvette"));
    list.add(new Car(749, "Buick", "Regal"));
    list.add(new Car(750, "Suzuki", "Esteem"));
    list.add(new Car(751, "Land Rover", "LR4"));
    list.add(new Car(752, "Chevrolet", "Silverado 2500"));
    list.add(new Car(753, "GMC", "1500 Club Coupe"));
    list.add(new Car(754, "Audi", "S6"));
    list.add(new Car(755, "Chevrolet", "Blazer"));
    list.add(new Car(756, "Ford", "F150"));
    list.add(new Car(757, "Lincoln", "Navigator"));
    list.add(new Car(758, "Lincoln", "Aviator"));
    list.add(new Car(759, "Oldsmobile", "Regency"));
    list.add(new Car(760, "Toyota", "FJ Cruiser"));
    list.add(new Car(761, "GMC", "Vandura 2500"));
    list.add(new Car(762, "Volkswagen", "Jetta"));
    list.add(new Car(763, "Chrysler", "Town & Country"));
    list.add(new Car(764, "Dodge", "Stratus"));
    list.add(new Car(765, "Mitsubishi", "Lancer Evolution"));
    list.add(new Car(766, "Lexus", "SC"));
    list.add(new Car(767, "Saturn", "VUE"));
    list.add(new Car(768, "Lincoln", "Navigator L"));
    list.add(new Car(769, "Porsche", "911"));
    list.add(new Car(770, "Chevrolet", "Avalanche"));
    list.add(new Car(771, "Mercedes-Benz", "600SL"));
    list.add(new Car(772, "Pontiac", "Firebird"));
    list.add(new Car(773, "Mitsubishi", "Mirage"));
    list.add(new Car(774, "Volkswagen", "Touareg"));
    list.add(new Car(775, "Suzuki", "Grand Vitara"));
    list.add(new Car(776, "Ford", "F250"));
    list.add(new Car(777, "Mercedes-Benz", "E-Class"));
    list.add(new Car(778, "GMC", "Sierra 2500"));
    list.add(new Car(779, "Toyota", "Yaris"));
    list.add(new Car(780, "Mazda", "Mazda3"));
    list.add(new Car(781, "Mitsubishi", "Pajero"));
    list.add(new Car(782, "Acura", "RL"));
    list.add(new Car(783, "Toyota", "Celica"));
    list.add(new Car(784, "Honda", "Accord"));
    list.add(new Car(785, "Tesla", "Roadster"));
    list.add(new Car(786, "Porsche", "Boxster"));
    list.add(new Car(787, "Chevrolet", "3500"));
    list.add(new Car(788, "Lincoln", "Continental"));
    list.add(new Car(789, "Subaru", "Legacy"));
    list.add(new Car(790, "Dodge", "Ram Van 2500"));
    list.add(new Car(791, "Volkswagen", "Jetta"));
    list.add(new Car(792, "Chevrolet", "Monte Carlo"));
    list.add(new Car(793, "Ford", "Freestyle"));
    list.add(new Car(794, "Toyota", "TundraMax"));
    list.add(new Car(795, "Chevrolet", "Silverado"));
    list.add(new Car(796, "Chevrolet", "1500"));
    list.add(new Car(797, "Lexus", "GS"));
    list.add(new Car(798, "Mazda", "Miata MX-5"));
    list.add(new Car(799, "Jensen", "Interceptor"));
    list.add(new Car(800, "Jeep", "Commander"));
    list.add(new Car(801, "Ford", "Mustang"));
    list.add(new Car(802, "Cadillac", "CTS"));
    list.add(new Car(803, "Shelby", "GT350"));
    list.add(new Car(804, "Cadillac", "XLR"));
    list.add(new Car(805, "Suzuki", "Swift"));
    list.add(new Car(806, "Chevrolet", "Corvette"));
    list.add(new Car(807, "Honda", "CR-V"));
    list.add(new Car(808, "Hyundai", "Accent"));
    list.add(new Car(809, "Nissan", "Maxima"));
    list.add(new Car(810, "Nissan", "Pathfinder"));
    list.add(new Car(811, "Dodge", "Ram 2500"));
    list.add(new Car(812, "Nissan", "Maxima"));
    list.add(new Car(813, "Nissan", "Maxima"));
    list.add(new Car(814, "Buick", "Terraza"));
    list.add(new Car(815, "MINI", "Clubman"));
    list.add(new Car(816, "Mitsubishi", "Montero"));
    list.add(new Car(817, "Mercedes-Benz", "GLK-Class"));
    list.add(new Car(818, "GMC", "Sierra 3500"));
    list.add(new Car(819, "Ford", "Econoline E250"));
    list.add(new Car(820, "Dodge", "Intrepid"));
    list.add(new Car(821, "Lexus", "SC"));
    list.add(new Car(822, "Chevrolet", "Cavalier"));
    list.add(new Car(823, "Audi", "R8"));
    list.add(new Car(824, "Oldsmobile", "Cutlass Cruiser"));
    list.add(new Car(825, "Acura", "NSX"));
    list.add(new Car(826, "Toyota", "MR2"));
    list.add(new Car(827, "Mazda", "B-Series"));
    list.add(new Car(828, "BMW", "5 Series"));
    list.add(new Car(829, "Volvo", "XC60"));
    list.add(new Car(830, "Pontiac", "Firebird"));
    list.add(new Car(831, "Chevrolet", "Suburban 2500"));
    list.add(new Car(832, "Chevrolet", "Blazer"));
    list.add(new Car(833, "Jeep", "Grand Cherokee"));
    list.add(new Car(834, "Chevrolet", "Corvette"));
    list.add(new Car(835, "Lexus", "IS"));
    list.add(new Car(836, "GMC", "Yukon XL 2500"));
    list.add(new Car(837, "Aston Martin", "Rapide"));
    list.add(new Car(838, "Mitsubishi", "Outlander"));
    list.add(new Car(839, "Mercury", "Mountaineer"));
    list.add(new Car(840, "Lincoln", "Town Car"));
    list.add(new Car(841, "Nissan", "240SX"));
    list.add(new Car(842, "Mercury", "Tracer"));
    list.add(new Car(843, "Dodge", "Ram 2500"));
    list.add(new Car(844, "Mercury", "Grand Marquis"));
    list.add(new Car(845, "Hyundai", "Genesis"));
    list.add(new Car(846, "Nissan", "Sentra"));
    list.add(new Car(847, "GMC", "3500"));
    list.add(new Car(848, "Eagle", "Summit"));
    list.add(new Car(849, "Toyota", "Camry"));
    list.add(new Car(850, "Chevrolet", "Express 3500"));
    list.add(new Car(851, "Mazda", "RX-8"));
    list.add(new Car(852, "Ford", "Windstar"));
    list.add(new Car(853, "Nissan", "Frontier"));
    list.add(new Car(854, "Mazda", "Mazda6"));
    list.add(new Car(855, "GMC", "1500"));
    list.add(new Car(856, "Mitsubishi", "Sigma"));
    list.add(new Car(857, "Chevrolet", "G-Series G10"));
    list.add(new Car(858, "Chevrolet", "Beretta"));
    list.add(new Car(859, "Buick", "Skylark"));
    list.add(new Car(860, "Chevrolet", "Colorado"));
    list.add(new Car(861, "Nissan", "Pathfinder"));
    list.add(new Car(862, "Audi", "TT"));
    list.add(new Car(863, "Lincoln", "Navigator"));
    list.add(new Car(864, "Mercury", "Mountaineer"));
    list.add(new Car(865, "Volvo", "XC90"));
    list.add(new Car(866, "Toyota", "Matrix"));
    list.add(new Car(867, "Infiniti", "QX"));
    list.add(new Car(868, "Porsche", "911"));
    list.add(new Car(869, "Chevrolet", "Camaro"));
    list.add(new Car(870, "Buick", "Riviera"));
    list.add(new Car(871, "Pontiac", "Grand Prix"));
    list.add(new Car(872, "Toyota", "Avalon"));
    list.add(new Car(873, "Eagle", "Talon"));
    list.add(new Car(874, "Ford", "Fairlane"));
    list.add(new Car(875, "Chevrolet", "Express 3500"));
    list.add(new Car(876, "Mercedes-Benz", "SLK-Class"));
    list.add(new Car(877, "Suzuki", "XL7"));
    list.add(new Car(878, "GMC", "Envoy"));
    list.add(new Car(879, "BMW", "M6"));
    list.add(new Car(880, "Jaguar", "XJ Series"));
    list.add(new Car(881, "Chevrolet", "G-Series 1500"));
    list.add(new Car(882, "Lexus", "LS Hybrid"));
    list.add(new Car(883, "Ford", "Mustang"));
    list.add(new Car(884, "Volvo", "V70"));
    list.add(new Car(885, "Lincoln", "MKX"));
    list.add(new Car(886, "Infiniti", "G35"));
    list.add(new Car(887, "Audi", "A6"));
    list.add(new Car(888, "Toyota", "Prius c"));
    list.add(new Car(889, "Cadillac", "SRX"));
    list.add(new Car(890, "MINI", "MINI"));
    list.add(new Car(891, "Pontiac", "Turbo Firefly"));
    list.add(new Car(892, "Isuzu", "Space"));
    list.add(new Car(893, "Audi", "S4"));
    list.add(new Car(894, "Dodge", "Viper"));
    list.add(new Car(895, "Subaru", "Impreza"));
    list.add(new Car(896, "Mercury", "Mountaineer"));
    list.add(new Car(897, "Porsche", "928"));
    list.add(new Car(898, "Acura", "RSX"));
    list.add(new Car(899, "Hyundai", "Azera"));
    list.add(new Car(900, "Aston Martin", "V12 Vantage"));
    list.add(new Car(901, "Buick", "LaCrosse"));
    list.add(new Car(902, "Volvo", "C70"));
    list.add(new Car(903, "Chevrolet", "Corvette"));
    list.add(new Car(904, "Mercedes-Benz", "R-Class"));
    list.add(new Car(905, "Acura", "RDX"));
    list.add(new Car(906, "Toyota", "Land Cruiser"));
    list.add(new Car(907, "Volkswagen", "Routan"));
    list.add(new Car(908, "Porsche", "911"));
    list.add(new Car(909, "Honda", "Accord"));
    list.add(new Car(910, "Volkswagen", "Jetta"));
    list.add(new Car(911, "Nissan", "300ZX"));
    list.add(new Car(912, "Volkswagen", "Jetta"));
    list.add(new Car(913, "Infiniti", "QX"));
    list.add(new Car(914, "Toyota", "T100"));
    list.add(new Car(915, "Pontiac", "Bonneville"));
    list.add(new Car(916, "GMC", "Savana 1500"));
    list.add(new Car(917, "Pontiac", "6000"));
    list.add(new Car(918, "Land Rover", "Range Rover"));
    list.add(new Car(919, "Peugeot", "207"));
    list.add(new Car(920, "Honda", "Odyssey"));
    list.add(new Car(921, "Honda", "Odyssey"));
    list.add(new Car(922, "GMC", "Savana 3500"));
    list.add(new Car(923, "GMC", "Acadia"));
    list.add(new Car(924, "Aston Martin", "V8 Vantage"));
    list.add(new Car(925, "Bentley", "Azure T"));
    list.add(new Car(926, "GMC", "Savana 3500"));
    list.add(new Car(927, "Dodge", "Ram 1500"));
    list.add(new Car(928, "Ford", "Club Wagon"));
    list.add(new Car(929, "Nissan", "200SX"));
    list.add(new Car(930, "Saab", "43711"));
    list.add(new Car(931, "Lexus", "LX"));
    list.add(new Car(932, "Plymouth", "Laser"));
    list.add(new Car(933, "Mercedes-Benz", "SLK-Class"));
    list.add(new Car(934, "Volvo", "C70"));
    list.add(new Car(935, "Jeep", "Wrangler"));
    list.add(new Car(936, "Volkswagen", "Golf III"));
    list.add(new Car(937, "Chevrolet", "Blazer"));
    list.add(new Car(938, "Pontiac", "Montana SV6"));
    list.add(new Car(939, "BMW", "6 Series"));
    list.add(new Car(940, "Suzuki", "Sidekick"));
    list.add(new Car(941, "Honda", "Civic Si"));
    list.add(new Car(942, "Acura", "TSX"));
    list.add(new Car(943, "GMC", "1500 Club Coupe"));
    list.add(new Car(944, "Mercury", "Marauder"));
    list.add(new Car(945, "Ford", "Mustang"));
    list.add(new Car(946, "Subaru", "Legacy"));
    list.add(new Car(947, "Nissan", "Quest"));
    list.add(new Car(948, "Hyundai", "Accent"));
    list.add(new Car(949, "Chevrolet", "Impala"));
    list.add(new Car(950, "Ford", "Mustang"));
    list.add(new Car(951, "Dodge", "Ram 2500"));
    list.add(new Car(952, "Chevrolet", "Blazer"));
    list.add(new Car(953, "Volvo", "XC70"));
    list.add(new Car(954, "Jeep", "Grand Cherokee"));
    list.add(new Car(955, "Mercedes-Benz", "300SL"));
    list.add(new Car(956, "Audi", "V8"));
    list.add(new Car(957, "Jeep", "Grand Cherokee"));
    list.add(new Car(958, "Honda", "Civic"));
    list.add(new Car(959, "Nissan", "Pathfinder"));
    list.add(new Car(960, "Mazda", "Miata MX-5"));
    list.add(new Car(961, "Chevrolet", "Sportvan G10"));
    list.add(new Car(962, "Saturn", "L-Series"));
    list.add(new Car(963, "GMC", "Sierra 3500"));
    list.add(new Car(964, "Buick", "Rainier"));
    list.add(new Car(965, "Saab", "9000"));
    list.add(new Car(966, "GMC", "1500"));
    list.add(new Car(967, "Infiniti", "EX"));
    list.add(new Car(968, "Lexus", "IS"));
    list.add(new Car(969, "Volvo", "XC70"));
    list.add(new Car(970, "Ford", "E350"));
    list.add(new Car(971, "Chevrolet", "Suburban 1500"));
    list.add(new Car(972, "Ford", "Th!nk"));
    list.add(new Car(973, "Subaru", "Outback"));
    list.add(new Car(974, "Chevrolet", "Aveo"));
    list.add(new Car(975, "Chevrolet", "Blazer"));
    list.add(new Car(976, "Volvo", "C30"));
    list.add(new Car(977, "Chevrolet", "Malibu"));
    list.add(new Car(978, "Toyota", "Supra"));
    list.add(new Car(979, "Oldsmobile", "Achieva"));
    list.add(new Car(980, "Hyundai", "Accent"));
    list.add(new Car(981, "Suzuki", "Sidekick"));
    list.add(new Car(982, "Mercedes-Benz", "SL-Class"));
    list.add(new Car(983, "Toyota", "Supra"));
    list.add(new Car(984, "Toyota", "Sienna"));
    list.add(new Car(985, "Chevrolet", "Malibu"));
    list.add(new Car(986, "Kia", "Spectra"));
    list.add(new Car(987, "Holden", "VS Commodore"));
    list.add(new Car(988, "Chrysler", "Crossfire"));
    list.add(new Car(989, "Chevrolet", "Suburban 2500"));
    list.add(new Car(990, "Honda", "Civic Si"));
    list.add(new Car(991, "GMC", "Acadia"));
    list.add(new Car(992, "Jaguar", "XJ"));
    list.add(new Car(993, "Toyota", "Tacoma"));
    list.add(new Car(994, "Ford", "Thunderbird"));
    list.add(new Car(995, "Kia", "Mohave/Borrego"));
    list.add(new Car(996, "Dodge", "Shadow"));
    list.add(new Car(997, "Ford", "Econoline E150"));
    list.add(new Car(998, "Chevrolet", "Silverado 3500"));
    list.add(new Car(999, "BMW", "Z4"));
    list.add(new Car(1000, "Buick", "Lucerne"));

    // sort list by Make
    Collections.sort(list, (c1, c2) -> c1.getMake().compareTo(c2.getMake()));

    performConditionally(list, car -> true, car -> System.out.println(car));
  }

  private static void performConditionally(
      List<Car> carList, Predicate<Car> predicate, Consumer<Car> consumer) {
    for (Car car : carList) {
      if (predicate.test(car)) {
        consumer.accept(car);
      }
    }
  }
}
