package com.example.stream.streamof;

import java.util.Arrays;
import java.util.List;

public class streamdistinct {

  public static void main(String[] args) {
    List<String> drugName =
        Arrays.asList(
            "OXYCODONE HYDROCHLORIDE AND ACETAMINOPHEN",
            "TITANIUM DIOXIDE and OCTINOXATE",
            "Penicillin G Potassium",
            "Loperamide Hydrochloride",
            "Psyllium Husk",
            "Diphenhydramine HCl",
            "GLYCERIN, ALLANTOIN",
            "Simvastatin",
            "HUMAN IMMUNEGLOBULIN G and HYALURONIDASE (HUMAN RECOMBINANT)",
            "Dantrolene Sodium",
            "Diphenhydramine Hydrochloride and Phenylephrine Hydrochloride",
            "Cefazolin",
            "furosemide",
            "ALUMINUM CHLOROHYDRATE",
            "Erythromycin",
            "Famotidine",
            "Lorazepam",
            "Undecylenic Acid",
            "metoprolol tartrate",
            "Lidocaine Hydrochloride",
            "Natural Medicine",
            "Treatment Set TS340074",
            "Citalopram",
            "metoprolol tartrate",
            "Adrenal, Allium cepa, Ambrosia artemisiaefolia",
            "Hydrocodone Bitartrate And Acetaminophen",
            "Phenol",
            "Melilotus officinalis, Spigelia anthelmia, Allium cepa, Belladonna, Bryonia, Cimicifuga racemosa, Gelsemium sempervirens, Glonoinum, Magnesia phosphorica, Nux vomica,",
            "CALCITRIOL",
            "ALCOHOL",
            "Ceftriaxone Sodium",
            "perampanel",
            "DAPTOMYCIN",
            "Guaifenesin",
            "Cefazolin",
            "Metformin Hydrochloride",
            "avobenzone, homosalate, octisalate, octocrylene",
            "Oxycodone Hydrochloride",
            "Simethicone",
            "Octinoxate and Oxybenzone",
            "Gabapentin",
            "Nizatidine",
            "ONDANSETRON HYDROCHLORIDE",
            "Levisticum e rad. 3",
            "Acetaminophen, Chlorpheniramine Maleate, and Phenylephrine Hydrochloride",
            "CALCIUM PHOSPHATE",
            "Adenosine",
            "Capsaicin",
            "Coagulation Factor VIIa (Recombinant)",
            "Clarithromycin",
            "White Mulberry",
            "ESCITALOPRAM OXALATE",
            "carmustine",
            "Mountain Cedar",
            "Ascorbic Acid, Cholecalciferol, Alpha-Tocopherol, Thiamine, Riboflavin, Niacinamide, Pyridoxine, Folic Acid, Cobalamin, Biotin, Pantothenic Acid, Zinc, Selenium",
            "diphenhydramine hydrochloride",
            "Pantoprazole Sodium",
            "Titanium Dioxide, Zinc Oxide",
            "Salicylic Acid",
            "Lidocaine Hydrochloride",
            "Anticoagulant Citrate Dextrose (ACD)",
            "Magnesium Sulfate",
            "Loperamide HCl",
            "RIFAMPIN",
            "Chlordiazepoxide Hydrochloride",
            "Dexamethasone",
            "Metformin Hydrochloride",
            "Calming Testers",
            "metolazone",
            "Indocyanine green",
            "Acetaminophen",
            "Octinoxate and Oxybenzone",
            "Aluminum Zirconium Tetrachlorohydrex Gly",
            "Aqua Foundation",
            "hydrocortisone",
            "Octinoxate, Octocrylene, Zinc Oxide",
            "Oxygen",
            "pioglitazone hydrochloride",
            "Bismuth Subsalicylate",
            "HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITALBA FLOWER, IMPATIENS GLANDULIFERA FLOWER, PRUNUS CERASIFERA FLOWER, AND ORNITHOGALUM UMBELLATUM",
            "Bismuth Subsalicylate",
            "Chlorpheniramine Maleate, Dextromethorphan Hydrobromide, Pseudoephedrine Hydrochloride",
            "Liver comp.",
            "amlodipine besylate and atorvastatin calcium",
            "ezogabine",
            "Ambrosia deltoides",
            "dextromethorphan hbr, guaifenesin, phenylephrine hcl",
            "Octinoxate and Titanium Dioxide",
            "Arnica Montana, Urtica Urens, Silicon Dioxide, and Thuja Occidentalis Root",
            "OCTINOXATE, Titanium dioxide, Zinc oxide",
            "METFORMIN HYDROCHLORIDE",
            "divalproex sodium",
            "OCTINOXATE",
            "BENZALKONIUM CHLORIDE",
            "Cetirizine Hydrochloride",
            "Codfish",
            "OCTINOXATE, OXYBENZONE, PADIMATE O",
            "Norethindrone",
            "Methocarbamol",
            "Isopropyl Alcohol",
            "Isopropyl Alcohol",
            "HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK",
            "ibuprofen",
            "Titanium Dioxide",
            "Atenolol",
            "Acetaminophen",
            "Menthol, Methyl salicylate",
            "ACETYLCYSTEINE",
            "ACONITUM NAPELLUS and EUCALYPTUS GLOBULUS LEAF and IPECAC",
            "ALCOHOL",
            "ALCOHOL",
            "ALCOHOL",
            "ALCOHOL",
            "ALCOHOL",
            "ALDESLEUKIN - BARIUM CARBONATE - CHASTE TREE - CHIMAPHILA UMBELLATA - CLEMATIS VITALBA - CONIUM MACULATUM FLOWERING TOP - DELPHINIUM STAPHISAGRIA SEED - DIGITALIS - FERRIC PICRATE - HUMAN INTERLEUKIN-",
            "ALTHAEA OFFICINALIS",
            "ALUMINUM CHLOROHYDRATE",
            "ALUMINUM SESQUICHLOROHYDRATE",
            "AMOXICILLIN AND CLAVULANATE POTASSIUM",
            "ARALIA QUINQUEFOLIA",
            "ARBUTINUM",
            "ARNICA MONTANA",
            "ATORVASTATIN CALCIUM",
            "ATRACURIUM BESYLATE",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen",
            "Acetaminophen and Pamabrom and Pyrilamine Maleate",
            "Acetylcysteine",
            "Acremonium Cephalosporium",
            "Acremonium strictum",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alcohol",
            "Alprostadil",
            "Aluminum Chlorohydrate",
            "Aluminum Chlorohydrate",
            "Aluminum Chlorohydrate",
            "Aluminum Sesquichlorohydrate",
            "Aluminum Sesquichlorohydrate",
            "Aluminum Zirconium Tetrachlorohydrex GLY",
            "Aluminum Zirconium Tetrachlorohydrex Gly",
            "Aluminum Zirconium Trichlorohydrex Gly",
            "American Cockroach",
            "Amikacin Sulfate",
            "Aminophylline Dihydrate",
            "Amlodipine Besylate",
            "Amlodipine Besylate",
            "Ammonia",
            "Amoxicillin and Clavulanate Potassium",
            "Ampicillin Sodium",
            "Ampicillin Sodium",
            "Anagrelide Hydrochloride",
            "Anticaries",
            "Anticoagulant Citrate Phosphate Dextrose Adenine",
            "Anticoagulant Citrate Phosphate Double Dextrose",
            "Apis Bryonia Special Order",
            "Aqua Foundation",
            "Arginine Hydrochloride",
            "Arizona Ash",
            "Arnica Aurum 20/30",
            "Arnica Montana",
            "Asparagus",
            "Aspergillus niger",
            "Aspirin",
            "Atenolol",
            "Atenolol",
            "Atenolol and Chlorthalidone",
            "Atomoxetine hydrochloride",
            "Azilsartan kamedoxomil",
            "BACILLUS ANTHRACIS IMMUNOSERUM RABBIT",
            "BENZALKONIUM CHLORIDE",
            "BENZALKONIUM CHLORIDE",
            "BENZALKONIUM CHLORIDE",
            "BUDESONIDE",
            "BUPRENORPHINE HYDROCHLORIDE",
            "Baclofen",
            "Benazepril Hydrochloride",
            "Benazepril Hydrochloride",
            "Benzalkonium Chloride",
            "Benzalkonium Chloride",
            "Benzalkonium Chloride",
            "Benzalkonium Chloride",
            "Benzalkonium Chloride",
            "Benzalkonium chloride",
            "Benzethonium chloride",
            "Benzocaine",
            "Benzocaine",
            "Benzocaine and Dextromethorphan Hydrobromide",
            "Benzoyl Peroxide",
            "Bethanechol Chloride",
            "Bethanechol Chloride",
            "Bisacodyl",
            "Bismuth Subsalicylate",
            "Black Birch",
            "BuPROPion Hydrochloride",
            "Buckwheat",
            "Bupivacaine Hydrochloride",
            "Bupropion Hydrochloride",
            "Buspirone Hydrochloride",
            "C Mold Mixture",
            "CALCIUM CHLORIDE",
            "CAPTOPRIL",
            "CARBOXYMETHYLCELLULOSE SODIUM",
            "CEPHALEXIN",
            "CHLOROXYLENOL",
            "CHLOROXYLENOL",
            "Calcium Chloride",
            "Calcium carbonate",
            "California Mugwort",
            "Camphor",
            "Camphor (Natural)",
            "Camphor Menthol Methyl Salicylate",
            "Carbamazepine",
            "Carelessweed",
            "Carvedilol",
            "Carvedilol",
            "Cedar Red",
            "Cefaclor",
            "Ceftriaxone Sodium",
            "Celecoxib",
            "Cephalexin",
            "Cephalexin",
            "Cephalexin",
            "Cetirizine",
            "Cetirizine Hydrochloride",
            "Cetirizine Hydrochloride",
            "Cetirizine Hydrochloride",
            "Chenodiol",
            "Chicken Meat Gallus sp.",
            "Chicken Meat Gallus sp.",
            "Chlorhexidine Gluconate",
            "Chlorpheniramine Maleate",
            "Chlorpheniramine Maleate",
            "Chlorpheniramine maleate pseudoephedrine HCl",
            "Chlorpromazine Hydrochloride",
            "Cilostazol",
            "Ciprofloxacin",
            "Ciprofloxacin Hydrochloride",
            "Ciprofloxacin hydrochloride",
            "Citalopram",
            "Citalopram",
            "Citalopram Hydrobromide",
            "Citalopram Hydrobromide",
            "Citalopram Hydrobromide",
            "Clam",
            "Common Sagebrush",
            "Couch Quack Grass",
            "Couch Quack Grass",
            "Cows Milk",
            "DELPHINIUM STAPHISAGRIA SEED",
            "DEXTROMETHORPHAN HYDROBROMIDE",
            "DIMETHICONE",
            "DIPYRIDAMOLE",
            "DOPAMINE HYDROCHLORIDE",
            "DOXERCALCIFEROL",
            "Dextromethorphan Hydrobromide",
            "Dextromethorphan Hydrobromide / Guaifenesin",
            "Dextromethorphan Hydrobromide and Guaifenesin",
            "Diabetic Pain Relieving",
            "Diclofenac Epolamine",
            "Diclofenac Sodium",
            "Dicyclomine Hydrochloride",
            "Diltiazem HCl",
            "Diltiazem Hydrochloride",
            "Diltiazem Hydrochloride",
            "Dimethicone",
            "Dimethicone",
            "Diphenhydramine",
            "Diphenhydramine HCl",
            "Diphenhydramine Hydrochloride",
            "Diphenhydramine Hydrochloride",
            "Diphenhydramine Hydrochloride",
            "Divalproex sodium",
            "Doxorubicin Hydrochloride",
            "Doxycycline hyclate",
            "Doxycycline hyclate",
            "Doxylamine succinate",
            "Duloxetine",
            "ETHYL ALCOHOL",
            "ETHYL ALCOHOL",
            "EUCALYPTOL THYMOL",
            "Eastern Cottonwood",
            "Enoxaparin Sodium",
            "Epinephrine",
            "Equisetum 10",
            "Ergocalciferol",
            "Erythromycin",
            "Erythromycin",
            "Etodolac",
            "Etodolac",
            "Etodolac",
            "Eucalyptol",
            "Ezetimibe",
            "FOMITOPSIS PINICOLA",
            "Famciclovir",
            "Famotidine",
            "Famotidine",
            "Famotidine",
            "Famotidine",
            "Fenofibrate",
            "Fenofibrate",
            "Fenofibric Acid",
            "Fentanyl buccal",
            "Ferrum Phos",
            "Fexofenadine HCl",
            "First Aid Ointment",
            "Fluocinonide",
            "Fluoride",
            "Fluoxetine Hydrochloride",
            "Fluoxetine Hydrochloride",
            "Fluticasone Propionate",
            "Folic Acid",
            "GENTIAN VIOLET",
            "GLIPIZIDE",
            "GLYCERIN",
            "GLYCERIN",
            "GUAIFENESIN",
            "Gabapentin",
            "Gabapentin",
            "Gabapentin",
            "Gemcitabine Hydrochloride",
            "Gemcitabine hydrochloride",
            "Gemfibrozil",
            "Gentamicin Sulfate",
            "Glyburide",
            "Glyburide",
            "Glyburide (micronized) and Metformin Hydrochloride",
            "Guaifenesin and Dextromethorphan Hydrobromide",
            "Guanfacine",
            "HUSKY 515",
            "HYDROGEN PEROXIDE",
            "HYDROMORPHONE HYDROCHLORIDE",
            "Haloperidol",
            "Hand Wash",
            "Hazelnut",
            "Hazelnut Pollen",
            "Helium",
            "Helminthosporium interseminatum",
            "Homatropine Hydrobromide",
            "Homeopathic Liquid",
            "Horse Epithelium",
            "Horse Fly",
            "House Dust",
            "House Dust",
            "Hydralazine Hydrochloride",
            "Hydralazine Hydrochloride",
            "Hydralazine Hydrochloride",
            "Hydralazine Hydrochloride",
            "Hydrocodone Bitartrate And Acetaminophen",
            "Hydrocortisone",
            "Hydrocortisone",
            "Hydrocortisone",
            "Hydrocortisone",
            "Hydrocortisone Acetate",
            "Hydrogen Peroxide",
            "Hydrogen Peroxide",
            "Hydromorphone Hydrochloride",
            "Hydroquinone",
            "Hydroxyzine",
            "Hydroxyzine Pamoate",
            "IRBESARTAN AND HYDROCHLOROTHIAZIDE",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Ibuprofen",
            "Indomethacin",
            "Indomethacin",
            "Intestaforce",
            "Iodides tincture",
            "Irbesartan",
            "Isoniazid",
            "Isoniazid",
            "Isopropyl Alcohol",
            "Isopropyl Alcohol",
            "Isosorbide Dinitrate",
            "Isosorbide Mononitrate",
            "Isosorbide Mononitrate",
            "Juniper Western",
            "KETOROLAC TROMETHAMINE",
            "Ketorolac Tromethamine",
            "Ketotifen Fumarate",
            "Ketotifen Fumarate",
            "LIDOCAINE HYDROCHLORIDE",
            "LISINOPRIL AND HYDROCHLOROTHIAZIDE",
            "LOMUSTINE",
            "LOPERAMIDE HYDROCHLORIDE",
            "LYTTA VESICATORIA",
            "Labetalol Hydrochloride",
            "Labetalol Hydrochloride",
            "Labetalol hydrochloride",
            "Lamotrigine",
            "Lamotrigine",
            "Lansoprazole",
            "Levofloxacin",
            "Levofloxacin",
            "Levonorgestrel",
            "Levothyroxine sodium",
            "Lidocaine",
            "Lidocaine",
            "Lidocaine Hydrochloride",
            "Lidocaine Hydrochloride",
            "Lidocaine Hydrochloride",
            "Lisinopril and Hydrochlorothiazide",
            "Lithium Carbonate",
            "Lithium Carbonate",
            "Lopinavir and Ritonavir",
            "Loratadine",
            "Loratadine",
            "Loratadine",
            "Loratadine",
            "Lorazepam",
            "Lorazepam",
            "Lorazepam",
            "Lovastatin",
            "Lycopodium Berberis",
            "Lycopodium Berberis",
            "MENTHOL",
            "METFORMIN HYDROCHLORIDE",
            "METHOTREXATE",
            "METHOTREXATE SODIUM",
            "METHYL SALICYLATE MENTHOL CAPSAICIN LIDOCAINE",
            "METOPROLOL SUCCINATE",
            "METRONIDAZOLE",
            "MINERAL OIL",
            "MITOXANTRONE HYDROCHLORIDE",
            "MORPHINE SULFATE",
            "MUCOR PLUMBEUS",
            "MULTIVITAMIN/MINERAL",
            "Magnesium Citrate",
            "Magnesium Sulfate",
            "Meclizine HCl",
            "Meclizine HCl",
            "Melatonin",
            "Melatonin",
            "Menthol",
            "Menthol",
            "Menthol",
            "Menthol",
            "Menthol and Pectin",
            "Menthol and Pectin",
            "Metformin Hydrochloride",
            "Metformin Hydrochloride",
            "Methimazole",
            "Methocarbamol",
            "Methotrexate",
            "Methotrexate",
            "Metoprolol Tartrate",
            "Metoprolol tartrate",
            "Metoprolol tartrate",
            "Metronidazole",
            "Metronidazole",
            "Miconazole nitrate",
            "Miconazole nitrate",
            "Midazolam hydrochloride",
            "Mineral Oil",
            "Mirtazapine",
            "Mixture of Seven Standardized Grasses",
            "Mycophenolate Mofetil",
            "NITROGEN",
            "NORTRIPTYLINE HYDROCHLORIDE",
            "Nabumentone",
            "Nabumetone",
            "Nabumetone",
            "Naloxone Hydrochloride",
            "Naltrexone Hydrochloride",
            "Naproxen",
            "Naproxen",
            "Naproxen Sodium",
            "Naproxen Sodium",
            "Naproxen sodium",
            "Nicotiana Carbo",
            "Nicotine Polacrilex",
            "Nicotine Polacrilex",
            "Nicotine polacrilex",
            "Nigrospora sphaerica",
            "Nitrous Oxide",
            "Norethindrone",
            "Norethindrone and ethinyl estradiol",
            "OCTINOXATE",
            "OCTINOXATE",
            "OCTINOXATE and TITANIUM DIOXIDE",
            "OCTINOXATE and TITANIUM DIOXIDE",
            "OLANZAPINE",
            "ONDANSETRON",
            "OXYCODONE HYDROCHLORIDE",
            "OXYGEN",
            "Oatmeal",
            "Octinoxate and Oxybenzone",
            "Octinoxate and Oxybenzone",
            "Octinoxate and Oxybenzone",
            "Octinoxate and Oxybenzone",
            "Octinoxate and Oxybenzone",
            "Octinoxate and Titanium Dioxide",
            "Ofloxacin",
            "Ofloxaxin",
            "Olanzapine",
            "Olanzapine",
            "Olanzapine",
            "Olanzapine",
            "Olanzapine",
            "Olanzapine",
            "Olive Pollen",
            "Omeprazole",
            "Omeprazole",
            "Ondansetron",
            "Ondansetron",
            "Ondansetron Hydrochloride",
            "Orange",
            "Ovaria Apis",
            "Oxycodone and Acetaminophen",
            "Oxygen",
            "Oxygen",
            "Oxygen",
            "Oxygen Helium Mixture 30/70",
            "Oxymetazoline Hydrochloride",
            "Oxymorphone Hydrochloride",
            "Oxymorphone Hydrochloride",
            "Oxymorphone hydrochloride",
            "PANTOPRAZOLE SODIUM",
            "PENTOXIFYLLINE",
            "PIPERACILLIN SODIUM and TAZOBACTAM SODIUM",
            "POTASSIUM BICARBONATE",
            "POTASSIUM CHLORIDE",
            "POVIDONE-IODINE",
            "PRAVASTATIN SODIUM",
            "PREGABALIN",
            "PROMETHAZINE HYDROCHLORIDE",
            "PULLULARIA PULLULANS",
            "PULLULARIA PULLULANS",
            "PYRITIONE ZINC",
            "Paroxetine",
            "Penicillin V Potassium",
            "Phenazopyridine HCl",
            "Phentermine Hydrochloride",
            "Phenylephrine HCl",
            "Piperacillin Sodium and Tazobactam Sodium",
            "Polyethylene Glycol 400",
            "Polyethylene Glycol 400 and Propylene Glycol",
            "Potassium Cation",
            "Potassium Chloride",
            "Prasugrel hydrochloride",
            "Pravastatin Sodium",
            "PredniSONE",
            "Prednisone",
            "Prednisone",
            "Probenecid",
            "Progesterone",
            "Promethazine Hydrochloride",
            "Promethazine Hydrochloride and Codeine Phosphate",
            "Propranolol Hydrochloride",
            "Pseudoephedrine HCl",
            "Pseudoephedrine HCl and Tripolidine",
            "Pseudoephedrine Hydrochloride",
            "Pyrithione Zinc",
            "Pyrithione Zinc",
            "Pyrithione Zinc",
            "Quinapril",
            "RAMEDICA",
            "RISPERIDONE",
            "RIVASTIGMINE TARTRATE",
            "Ragweed Slender",
            "Red Mulberry",
            "Rhodotorula mucilaginosa",
            "Risperidone",
            "Ropinirole Hydrochloride",
            "Rosuvastatin calcium",
            "Rosuvastatin calcium",
            "SAFFRON",
            "SALICYLIC ACID",
            "SALICYLIC ACID",
            "SERTRALINE",
            "SERTRALINE HYDROCHLORIDE",
            "SIMVASTATIN",
            "SODIUM CITRATE and CITRIC ACID MONOHYDRATE",
            "SODIUM FLUORIDE",
            "SODIUM MONOFLUOROPHOSPHATE",
            "SODIUM MONOFLUOROPHOSPHATE",
            "SODIUM MONOFLUOROPHOSPHATE",
            "SOTALOL HYDROCHLORIDE",
            "ST JOHNS WORT",
            "STANNOUS FLUORIDE",
            "STRYCHNOS IGNATII SEED",
            "SULFUR",
            "Salicylic Acid",
            "Salicylic Acid",
            "Salicylic Acid",
            "Salicylic acid",
            "Selenium sulfide",
            "Sennosides",
            "Sennosides and Docusate Sodium",
            "Sertraline Hydrochloride",
            "Sertraline Hydrochloride",
            "Short Ragweed Pollen",
            "Simethicone",
            "Simethicone",
            "Simethicone 180 mg",
            "Simvastatin",
            "Simvastatin",
            "Skin Protectant",
            "Sodium Bicarbonate",
            "Sodium Fluoride",
            "Sodium Fluoride",
            "Sodium Fluoride",
            "Sodium Fluoride",
            "Sodium Fluoride",
            "Sodium Hypochlorite",
            "Sodium Polystyrene Sulfonate",
            "Sodium fluoride",
            "Sodium monofluorophosphate",
            "Stannum 17 Special Order",
            "Streptomycin",
            "Sulfur",
            "Sulindac",
            "TAMSULOSIN HYDROCHLORIDE",
            "TECHNETIUM TC-99M SODIUM PERTECHNETATE",
            "TELMISARTAN AND HYDROCHLOROTHIAZIDE",
            "TERBUTALINE SULFATE",
            "TITANIUM DIOXIDE",
            "TITANIUM DIOXIDE",
            "TOLNAFTATE",
            "TRIAMCINOLONE ACETONIDE",
            "TRICLOCARBAN",
            "TRICLOSAN",
            "TRICON",
            "Telmisartan",
            "Tetracycline HCl",
            "Tetracycline Hydrochloride",
            "Tetracycline Hydrochloride",
            "Thiothixene",
            "Thuja Occidentalis",
            "Thymus (Suis)",
            "Titanium Dioxide",
            "Titanium Dioxide and Octinoxate",
            "Titanium Dioxide and Zinc Oxide",
            "Titanium dioxide",
            "Titanium dioxide",
            "Titanium dioxide",
            "Tolnaftate",
            "Topical Analgesic",
            "Topiramate",
            "Torsemide",
            "Tramadol Hydrochloride",
            "Tramadol Hydrochloride and Acetaminophen",
            "Tramadol hydrochloride and acetaminophen",
            "Traumeel",
            "Trazodone Hydrochloride",
            "Trazodone Hydrochloride",
            "Trazodone Hydrochloride",
            "Treatment Set TS348982",
            "Treatment Set TS349632",
            "Treatment Set TS349778",
            "Tretinoin",
            "Tretinoin",
            "Trichophyton schoenleinii",
            "Triclosan",
            "Triclosan",
            "Triclosan",
            "Triclosan",
            "Triclosan",
            "Triclosan",
            "Trifluoperazine Hydrochloride",
            "Trihexyphenidyl Hydrochloride",
            "Trimipramine Maleate",
            "Tropicamide",
            "Trospium Chloride",
            "Trospium Chloride",
            "Tylenol Cough and Sore Throat",
            "Urea",
            "Urea",
            "Urea",
            "Ursodiol",
            "VENLAFAXINE HYDROCHLORIDE",
            "VENLAFAXINE HYDROCHLORIDE",
            "VENLAFAXINE HYDROCHLORIDE",
            "Valproic Acid",
            "Vanilla",
            "Venlafaxine",
            "Verapamil Hydrochloride",
            "Virginia Live Oak",
            "Viscum 1",
            "WATER",
            "Warfarin Sodium",
            "Water",
            "West Wheat Grass",
            "Wheat Smut",
            "Wheat Smut",
            "White Alder",
            "White Ash",
            "White Faced Hornet hymenoptera venom Venomil Maintenance",
            "White Mulberry",
            "ZINC OXIDE",
            "ZINC OXIDE",
            "ZINC OXIDE",
            "ZINC OXIDE",
            "Zinc Oxide",
            "Zinc Oxide",
            "Zinc Oxide and Titanium Dioxide",
            "Zinc oxide",
            "Ziprasidone hydrochloride",
            "Zolmitriptan",
            "Zolmitriptan",
            "abacavir sulfate and lamivudine",
            "acetaminophen",
            "alcohol",
            "alendronate sodium",
            "amlodipine and benazepril hydrochloride",
            "amlodipine besylate and atorvastatin calcium",
            "ampicillin sodium",
            "ampicillin sodium and sulbactam sodium",
            "atorvastatin calcium",
            "baclofen",
            "benzocaine",
            "benzonatate",
            "benzonatate",
            "benzonatate",
            "bupropion hydrochloride",
            "calcium carbonate",
            "capsaicin",
            "cetirizine Hydrochloride",
            "cetirizine hydrochloride",
            "cetirizine hydrochloride",
            "cholestyramine",
            "cinacalcet hydrochloride",
            "ciprofloxacin",
            "ciprofloxacin",
            "ciprofloxacin",
            "clindamycin hydrochloride",
            "clindamycin phosphate",
            "clindamycin phosphate and benzoyl peroxide",
            "clindamycin phosphate and benzoyl peroxide",
            "clonidine hydrochloride",
            "clopidogrel",
            "clopidogrel bisulfate",
            "clozapine",
            "cyclobenzaprine hydrochloride",
            "darbepoetin alfa",
            "dextroamphetamine sulfate",
            "didanosine enteric-coated beadlets",
            "diltiazem hydrochloride",
            "divalproex sodium",
            "doxazosin mesylate",
            "doxepin hydrochloride",
            "doxycycline",
            "erythromycin and benzoyl peroxide",
            "estradiol",
            "ethyl alcohol",
            "everolimus",
            "famotidine",
            "fexofenadine hcl",
            "fexofenadine hydrochloride and pseudoephedrine hydrochloride",
            "follitropin",
            "fomepizole",
            "furosemide",
            "gabapentin",
            "galantamine hydrobromide",
            "galantamine hydrobromide",
            "glimepiride",
            "glucagon hydrochloride",
            "hydrochlorothiazide",
            "hydrocortisone",
            "hydrocortisone",
            "hydrocortisone acetate pramoxine hcl",
            "hydromorphone hydrochloride",
            "hydroxyzine hydrochloride",
            "ibandronate sodium",
            "idursulfase",
            "iloperidone",
            "influenza virus vaccine",
            "insulin aspart",
            "isoxsuprine hydrochloride",
            "lansoprazole",
            "lansoprazole",
            "levetiracetam",
            "levofloxacin",
            "levothyroxine sodium tablets",
            "lisinopril",
            "megestrol acetate",
            "memantine hydrochloride",
            "menthol",
            "methylergonovine maleate",
            "methylphenidate hydrochloride",
            "methylphenidate hydrochloride",
            "metoprolol tartrate and hydrochlorothiazide",
            "minocycline hydrochloride",
            "modafinil",
            "moexipril hydrochloride",
            "moexipril hydrochloride",
            "morphine sulfate",
            "moxifloxacin hydrochloride",
            "nifedipine",
            "nifedipine",
            "nitric oxide",
            "nitroglycerin",
            "nitroglycerin",
            "not applicable",
            "olmesartan medoxomil",
            "oxycodone hydrochloride",
            "oxycodone hydrochloride and acetaminophen",
            "oxymetazoline hydrochloride",
            "pancrelipase",
            "paroxetine hydrochloride",
            "paroxetine hydrochloride",
            "paroxetine hydrochloride",
            "penicillin G potassium",
            "perampanel",
            "pinus strobus pollen",
            "pioglitazone and metformin hydrochloride",
            "piroxicam",
            "polyethylene glycol 0.4% and propylene glycol 0.3%",
            "potassium chloride",
            "potassium chloride",
            "potassium nitrate and sodium fluoride",
            "povidone-iodine",
            "prochlorperazine maleate",
            "ranitidine hydrochloride",
            "riluzole",
            "romiplostim",
            "ropinirole",
            "ropinirole hydrochloride",
            "ropinirole hydrochloride",
            "scopolamine",
            "sevelamer hydrochloride",
            "silver sulfadiazine",
            "simvastatin",
            "simvastatin",
            "sitagliptin",
            "sodium chloride",
            "sodium fluoride",
            "somatropin",
            "spironolactone",
            "spironolactone",
            "spironolactone and hydrochlorothiazide",
            "stannous fluoride",
            "stavudine",
            "tamsulosin hydrochloride",
            "tapentadol hydrochloride",
            "tiagabine hydrochloride",
            "tolbutamide",
            "tolterodine tartrate",
            "tramadol hydrochloride and acetaminophen",
            "treprostinil",
            "trifluoperazine hydrochloride",
            "ustilago maydis",
            "valproic acid",
            "valsartan and hydrochlorothiazide",
            "vecuronium bromide",
            "verapamil hydrochloride",
            "vilazodone hydrochloride",
            "water",
            "zinc oxide",
            "ziprasidone hydrochloride",
            "zolpidem tartrate",
            "zolpidem tartrate");

    drugName
        .stream()
        .map(x -> x.toLowerCase())
        .distinct()
        .sorted()
        .forEach(x -> System.out.println(x));
  }
}
