package com.example.stream.streamof;

import java.util.Arrays;
import java.util.List;

public class streammapforeach {

  public static void main(String[] args) {
    List<String> drugName =
        Arrays.asList(
            "OXYCODONE HYDROCHLORIDE AND ACETAMINOPHEN",
            "TITANIUM DIOXIDE and OCTINOXATE",
            "Penicillin G Potassium",
            "Loperamide Hydrochloride",
            "Psyllium Husk",
            "Diphenhydramine HCl",
            "GLYCERIN, ALLANTOIN",
            "Simvastatin",
            "HUMAN IMMUNEGLOBULIN G and HYALURONIDASE (HUMAN RECOMBINANT)",
            "Dantrolene Sodium",
            "Diphenhydramine Hydrochloride and Phenylephrine Hydrochloride",
            "Cefazolin",
            "furosemide",
            "ALUMINUM CHLOROHYDRATE",
            "Erythromycin",
            "Famotidine",
            "Lorazepam",
            "Undecylenic Acid",
            "metoprolol tartrate",
            "Lidocaine Hydrochloride",
            "Natural Medicine",
            "Treatment Set TS340074",
            "Citalopram",
            "metoprolol tartrate",
            "Adrenal, Allium cepa, Ambrosia artemisiaefolia",
            "Hydrocodone Bitartrate And Acetaminophen",
            "Phenol",
            "Melilotus officinalis, Spigelia anthelmia, Allium cepa, Belladonna, Bryonia, Cimicifuga racemosa, Gelsemium sempervirens, Glonoinum, Magnesia phosphorica, Nux vomica,",
            "CALCITRIOL",
            "ALCOHOL",
            "Ceftriaxone Sodium",
            "perampanel",
            "DAPTOMYCIN",
            "Guaifenesin",
            "Cefazolin",
            "Metformin Hydrochloride",
            "avobenzone, homosalate, octisalate, octocrylene",
            "Oxycodone Hydrochloride",
            "Simethicone",
            "Octinoxate and Oxybenzone",
            "Gabapentin",
            "Nizatidine",
            "ONDANSETRON HYDROCHLORIDE",
            "Levisticum e rad. 3",
            "Acetaminophen, Chlorpheniramine Maleate, and Phenylephrine Hydrochloride",
            "CALCIUM PHOSPHATE",
            "Adenosine",
            "Capsaicin",
            "Coagulation Factor VIIa (Recombinant)",
            "Clarithromycin",
            "White Mulberry",
            "ESCITALOPRAM OXALATE",
            "carmustine",
            "Mountain Cedar",
            "Ascorbic Acid, Cholecalciferol, Alpha-Tocopherol, Thiamine, Riboflavin, Niacinamide, Pyridoxine, Folic Acid, Cobalamin, Biotin, Pantothenic Acid, Zinc, Selenium",
            "diphenhydramine hydrochloride",
            "Pantoprazole Sodium",
            "Titanium Dioxide, Zinc Oxide",
            "Salicylic Acid",
            "Lidocaine Hydrochloride",
            "Anticoagulant Citrate Dextrose (ACD)",
            "Magnesium Sulfate",
            "Loperamide HCl",
            "RIFAMPIN",
            "Chlordiazepoxide Hydrochloride",
            "Dexamethasone",
            "Metformin Hydrochloride",
            "Calming Testers",
            "metolazone",
            "Indocyanine green",
            "Acetaminophen",
            "Octinoxate and Oxybenzone",
            "Aluminum Zirconium Tetrachlorohydrex Gly",
            "Aqua Foundation",
            "hydrocortisone",
            "Octinoxate, Octocrylene, Zinc Oxide",
            "Oxygen",
            "pioglitazone hydrochloride",
            "Bismuth Subsalicylate",
            "HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITALBA FLOWER, IMPATIENS GLANDULIFERA FLOWER, PRUNUS CERASIFERA FLOWER, AND ORNITHOGALUM UMBELLATUM",
            "Bismuth Subsalicylate",
            "Chlorpheniramine Maleate, Dextromethorphan Hydrobromide, Pseudoephedrine Hydrochloride",
            "Liver comp.",
            "amlodipine besylate and atorvastatin calcium",
            "ezogabine",
            "Ambrosia deltoides",
            "dextromethorphan hbr, guaifenesin, phenylephrine hcl",
            "Octinoxate and Titanium Dioxide",
            "Arnica Montana, Urtica Urens, Silicon Dioxide, and Thuja Occidentalis Root",
            "OCTINOXATE, Titanium dioxide, Zinc oxide",
            "METFORMIN HYDROCHLORIDE",
            "divalproex sodium",
            "OCTINOXATE",
            "BENZALKONIUM CHLORIDE",
            "Cetirizine Hydrochloride",
            "Codfish",
            "OCTINOXATE, OXYBENZONE, PADIMATE O",
            "Norethindrone",
            "Methocarbamol",
            "Isopropyl Alcohol",
            "Isopropyl Alcohol",
            "HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK",
            "ibuprofen",
            "Titanium Dioxide",
            "Atenolol",
            "Acetaminophen",
            "Menthol, Methyl salicylate");

    drugName
        .stream()
        .filter(x -> x.startsWith("A"))
        .map(x -> x.toLowerCase())
        .forEach(System.out::println);
  }
}
